# Generated by Django 5.0.3 on 2025-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='ageRating',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='publishedDate',
            field=models.DateField(default='2025-04-09'),
        ),
    ]
