# Generated by Django 5.0.3 on 2025-04-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0002_moviemodel_agerating_moviemodel_publisheddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='publishedDate',
            field=models.DateField(default='2025-04-13'),
        ),
    ]
