# Generated by Django 5.0.3 on 2025-04-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0003_alter_moviemodel_publisheddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='publishedDate',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='publishYear',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
