# Generated by Django 5.0.3 on 2025-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0004_remove_moviemodel_publisheddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='director',
            field=models.CharField(default='Режиссер не указан', max_length=50),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='duration',
            field=models.CharField(default='Длительность сеанса не указана', max_length=5),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='language',
            field=models.CharField(default='Англиский', max_length=50),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='production',
            field=models.CharField(default='Страна производителя не указана', max_length=50),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='scenarist',
            field=models.CharField(default='Сценарист не указан', max_length=50),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='studio',
            field=models.CharField(default='Студия не указана', max_length=50),
        ),
    ]
