# Generated by Django 5.0.3 on 2025-04-17 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0005_moviemodel_director_moviemodel_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCommentModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='CinemaApp.moviemodel')),
            ],
        ),
    ]
