# Generated by Django 5.0.3 on 2025-04-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0007_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='12345', max_length=100),
        ),
    ]
