# Generated by Django 5.0.3 on 2025-04-25 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0008_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecommentmodel',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.usermodel'),
        ),
    ]
