# Generated by Django 5.0.3 on 2025-04-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0009_moviecommentmodel_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='poster',
            field=models.ImageField(default='images/posters/default.PNG', upload_to='images/posters/'),
        ),
    ]
