# Generated by Django 5.0.3 on 2025-05-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0010_moviemodel_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecommentmodel',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
