# Generated by Django 5.0.3 on 2025-05-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0011_moviecommentmodel_rating_moviemodel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
