# Generated by Django 5.0.3 on 2025-05-12 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0012_cinemamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='cinemaAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='CinemaApp.cinemamodel'),
        ),
    ]
