# Generated by Django 5.0.3 on 2025-05-15 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0013_usermodel_cinemaadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaRoomModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cinemaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.cinemamodel')),
            ],
        ),
    ]
