# Generated by Django 5.0.3 on 2025-05-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0014_cinemaroommodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaroommodel',
            name='seats',
            field=models.JSONField(default=dict),
        ),
    ]
