# Generated by Django 5.0.3 on 2025-05-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0015_cinemaroommodel_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaroommodel',
            name='nextFilm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='CinemaApp.moviemodel'),
        ),
        migrations.AddField(
            model_name='cinemaroommodel',
            name='nextFilmTime',
            field=models.DateTimeField(null=True),
        ),
    ]
