# Generated by Django 5.0.3 on 2025-05-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0016_cinemaroommodel_nextfilm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemaroommodel',
            old_name='seats',
            new_name='defaultSeats',
        ),
        migrations.RemoveField(
            model_name='cinemaroommodel',
            name='nextFilm',
        ),
        migrations.RemoveField(
            model_name='cinemaroommodel',
            name='nextFilmTime',
        ),
    ]
