# Generated by Django 5.0.3 on 2025-05-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0017_rename_seats_cinemaroommodel_defaultseats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmSessionModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sessionTime', models.DateTimeField(null=True)),
                ('seats', models.JSONField(default=dict)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.moviemodel')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.cinemaroommodel')),
            ],
        ),
    ]
