# Generated by Django 5.0.3 on 2025-05-30 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0018_filmsessionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmsessionmodel',
            name='cinemaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.cinemamodel'),
        ),
    ]
