# Generated by Django 5.0.3 on 2025-06-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0020_usermodel_email_alter_usermodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmTicketModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seatType', models.CharField(max_length=1)),
                ('seatRowIndex', models.PositiveIntegerField()),
                ('seatIndex', models.PositiveIntegerField()),
                ('filmSessionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.filmsessionmodel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.usermodel')),
            ],
        ),
    ]
