# Generated by Django 5.0.3 on 2025-06-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0021_filmticketmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmticketmodel',
            name='seatNumber',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
