# Generated by Django 5.0.3 on 2025-06-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0022_filmticketmodel_seatnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemamodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='CinemaComingSoonModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('closestSessionTime', models.DateField()),
                ('cinemaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.cinemamodel')),
                ('filmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CinemaApp.moviemodel')),
            ],
        ),
    ]
