# Generated by Django 5.0.3 on 2025-07-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0023_cinemamodel_description_cinemacomingsoonmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaroommodel',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
